on: push
name: Build and publish
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: install
    - name: Build
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run build --prod
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        FOLDER: dist/f10k
        BRANCH: gh-pages
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
