on: push
name: Build and publish
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: install
    - name: Build
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run build --prod
    - name: dockerize
      uses: pangzineng/Github-Action-One-Click-Docker@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE_NAME: f10k
        DOCKER_IMAGE_TAG: latest
        
