on: push
name: Build and publish
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: install
    - name: Build
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run build --prod
    - uses: actions/upload-artifact@master
      with: 
        name: dist
        path: ./dist
        
  dockerize:
    name: Dockerize
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: dist
        path: ./dist
    - name: Docker login
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE_NAME: f10k
        DOCKER_IMAGE_TAG: latest
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
    - name: Docker build
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE_NAME: f10k
        DOCKER_IMAGE_TAG: latest
      run: |
        docker build -t '$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG' .
    - name: Docker deploy
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE_NAME: f10k
        DOCKER_IMAGE_TAG: latest
      run: |
        docker push '{DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG'
        
